config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :users do
    collection do
      get :subscribe_other
      get :following, :followers
      get :profile
    end
  end
  resources :photos
  resources :relationships
  root 'users#index'
  

end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :user
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :photos
  has_many :active_relationships, class_name:  "Relationship",
                                  foreign_key: "follower_id",
                                  dependent:   :destroy
  has_many :passive_relationships, class_name:  "Relationship",
                                   foreign_key: "followed_id",
                                   dependent:   :destroy

  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower                                  

  has_attached_file :profile_image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :profile_image, content_type: /\Aimage\/.*\Z/ 

  def feed
    Photo.where("user_id IN (:following_ids) OR user_id = :user_id",
                following_ids: following_ids, user_id: id)
  end

  def follow(other_user)
    active_relationships.create(followed_id: other_user.id)
  end

  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  def following?(other_user)
    following.include?(other_user)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_devise_permitted_parameters, if: :devise_controller?

  protected

  def configure_devise_permitted_parameters
    registration_params = [:name,:profile_image, :email, :password, :password_confirmation]

    if params[:action] == 'update'
      devise_parameter_sanitizer.for(:account_update) { 
        |u| u.permit(registration_params << :current_password)
      }
    elsif params[:action] == 'create'
      devise_parameter_sanitizer.for(:sign_up) { 
        |u| u.permit(registration_params) 
      }
    end
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  layout 'home'
  def new
    @photo = Photo.new
  end

  def create
    @photo = Photo.new(photo_params)

    if @photo.save!
      redirect_to users_path
    else
      flash[:notice] = "upload error"
    end

  end

  def delete
  end

  private
    def photo_params
      params.require(:photo).permit(:image,:image_caption,:user_id)
    end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

  def create
    @user = User.find(params[:followed_id])
    current_user.follow(@user)
    respond_to do |format|
      format.html { redirect_to @user }
      format.js
    end
  end

  def destroy
    @user = Relationship.find(params[:id]).followed
    current_user.unfollow(@user)
    respond_to do |format|
      format.html { redirect_to @user }
      format.js
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  layout 'home'
  
  def index
    if current_user
     @user = current_user
   else
     redirect_to new_user_session_path, notice: 'You are not logged in.'
   end
  end

  def edit
  end

  def show 
    @user = User.find(params[:id])
  end

  def subscribe_other
    @users = User.all
  end

  def profile
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PhotoApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tags %>
</head>
<body>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>

app/views/layouts/home.html.haml
!!!
%html
  %head
    %meta{:charset => "utf-8"}
    %meta{:content => "IE=edge", "http-equiv" => "X-UA-Compatible"}
    %title PhotoApp
    = stylesheet_link_tag "application" , :media => "all"
    = csrf_meta_tags
    = javascript_include_tag "application", "data-turbolinks-track" => true
    %meta{:content => "width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no", :name => "viewport"}
  %body{:class => "hold-transition skin-black sidebar-mini","data-no-turbolink" => "true"}
    .wrapper
      = render "shared/navigation/topnavigation.html.haml"
      / .content-wrapper
      /   / =render :partial => "shared/navigation/messages"
      = yield
      %footer.main-footer
        .pull-right.hidden-xs
          %b Version
          x.x.x
        %strong
          Copyright &copy; 2015-2016
          = succeed "." do
            %a{:href => '#'} PhotoApp
        All rights reserved.      

app/views/photos/delete.html.erb
<h1>Photos#delete</h1>
<p>Find me in app/views/photos/delete.html.erb</p>

app/views/photos/new.html.haml
= form_for @photo do |f|
  .form-group
    .col-sm-4
      = image_tag("upload.png", :width=>"200", :height=>"200", :class=>"thumb", :onclick=>"$(this).parent().find('.profile_pic').click();")
      = f.file_field :image, :style=>"visibility:hidden", :class => "profile_pic", :onchange =>"readURL(this)"
      =f.text_field :image_caption, class: 'form-control', autofocus: true, placeholder: 'Add Caption...' 
      = f.hidden_field :user_id, :value => current_user.id
      %br
      = f.button "Upload", :class => 'btn btn-info' 


:javascript
  function readURL(input) {
    
    if (input.files && input.files[0]) {
        var reader = new FileReader();
        
        reader.onload = function (e) {
            $(input).parent().find(".thumb").attr('src', e.target.result);
        }
           
        reader.readAsDataURL(input.files[0]);
    }
  }

app/views/relationships/create.js.haml
$("#follow_form").html("#{escape_javascript(render('users/unfollow'))}");
$("#followers").html('#{@user.followers.count}');

app/views/relationships/destroy.js.haml
$("#follow_form").html("#{escape_javascript(render('users/follow'))}");
$("#followers").html('#{@user.followers.count}');

app/views/shared/navigation/_topnavigation.html.haml
%nav.navbar.navbar-default
  .navbar-container
    .navbar-header
      %button.navbar-toggle.collapsed{"data-target" => "#bs-navbar-collapse-1", "data-toggle" => "collapse", type: "button"}
        %span.sr-only Toggle Navigation
        %span.icon-bar
        %span.icon-bar
      .navbar-brand= link_to "#{current_user.name.capitalize}'s PhotoApp", root_path
    .collapse.navbar-collapse#bs-navbar-collapse-1
      %ul.nav.navbar-nav.navbar-right
        %li
          = link_to "Add New Photo",new_photo_path
        %li
          = link_to "Profile", profile_users_path(:id => current_user.id)
        %li
          = link_to "Susbcribe Others", subscribe_other_users_path
        %li
          = link_to "Sign Out", destroy_user_session_path, :method => :get
        %li
          .polroid
            %img{:alt => "...", :src => current_user.profile_image.url,height: 40,width: 40,style: "border-radius: 50%"}  

app/views/users/_follow.html.haml
= form_for(current_user.active_relationships.build, remote: true) do |f|
  = hidden_field_tag :followed_id, @user.id
  = f.submit "Follow", class: "btn btn-primary"

app/views/users/_stats.html.haml
- @user ||= current_user
%h3
  .stats
    %a{:href => "#"}
      %strong#following.stat
        = @user.following.count
      Following
    %hr  
    %a{:href => "#"}
      %strong#followers.stat
        = @user.followers.count
      Followers

app/views/users/_unfollow.html.haml
= form_for(current_user.active_relationships.find_by(followed_id: @user.id),html: { method: :delete },remote: true) do |f|                                                       
  = f.submit "Unfollow", class: "btn"

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.haml
.col-md-1
  %h3
    = current_user.name.capitalize
  %img{:alt => "...", :src => current_user.profile_image.url,height: 100,width: 100,style: "border-radius: 50%"}
  = render 'stats'
- if current_user.following.any?
  .back-cover
    - sorted_photo_ids=[]
    - @user.following.each do |following_user|
      - following_user.photos.each do |photo|
        - sorted_photo_ids << photo.id
        - sorted_photo_ids.sort!
    - sorted_photo_ids.reverse!    
    .photo-container
      %br
      .row
        .col-md-4
          .polaroid
            - sorted_photo_ids.each do |photo_id|
              - photo = Photo.find(photo_id)
              %h3
                = photo.user.name.capitalize
                %img{:alt => "...", :src => photo.user.profile_image.url,height: 40,width: 40,style: "border-radius: 50%"}
              %img.profile{:alt => "...", :src => Photo.find(photo_id).image.url,height: 300,width: 300}
                - if photo.created_at > Time.now.beginning_of_day
                  %strong{style: "color: black"}
                    = "#{time_ago_in_words(photo.created_at)} ago"
                - else
                  %strong{style: "color: black"}
                    = photo.created_at.strftime("%b %d, %Y")  
- else
  %h1
    Please follow someone to get feed    
  

app/views/users/profile.html.haml
.col-md-1
  %h3
    = @user.name.capitalize
  %img{:alt => "...", :src => @user.profile_image.url,height: 100,width: 100,style: "border-radius: 50%"}
  = render 'stats'
  - unless current_user.id == @user.id
    #follow_form
      - if current_user.following?(@user)
        = render 'unfollow'
      - else
        = render 'follow'

- if @user.photos.any?  
  .back-cover
    - sorted_photo_ids=[]
    - @user.photos.each do |photo|
      - sorted_photo_ids << photo.id
      - sorted_photo_ids.sort!
    - sorted_photo_ids.reverse!    
    .photo-container
      %br
      .row
        .col-md-4
          .polaroid
            - sorted_photo_ids.each do |photo_id|
              - photo = Photo.find(photo_id)
              %h3
                = photo.user.name.capitalize
                %img{:alt => "...", :src => photo.user.profile_image.url,height: 40,width: 40,style: "border-radius: 50%"}
              %img.profile{:alt => "...", :src => Photo.find(photo_id).image.url,height: 300,width: 300}
                - if photo.created_at > Time.now.beginning_of_day
                  %strong{style: "color: black"}
                    = "#{time_ago_in_words(photo.created_at)} ago"
                - else
                  %strong{style: "color: black"}
                    = photo.created_at.strftime("%b %d, %Y")
- else
  %h1
    This USER has not updated any photo yet
            

app/views/users/show.html.haml
- provide(:title, @user.name)
.row
  %aside.col-md-4
    %section
      %h1
        %img{:alt => "...", :src => current_user.profile_image.url,height: 40,width: 40,style: "border-radius: 50%"}
        = @user.name
    %section.stats
      = render 'stats'
  .col-md-8
    = render 'follow_form' if logged_in?
    - if @user.photos.any?
      %h3
        Microposts (#{@user.photos.count})
      %ol.microposts
        = render @microposts
      = will_paginate @microposts

app/views/users/subscribe_other.html.haml
%table.table.table-responsive.table-bordered
  %thead
    %tr
      %th Name
      %th Profile picture
      %th Sub
  %tbody
    - @users.each do |user|
      - unless current_user.id == user.id
        %tr{:class=> "info"}
          %td
            = user.name.capitalize
          %td
            %img{:alt => "...", :src => user.profile_image.url,height: 40,width: 40,style: "border-radius: 50%"}
          %td
            = link_to profile_users_path(:id => user.id) do
              .btn.btn-primary
                View Profile